# Generated by Django 3.2.20 on 2023-07-24 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=150)),
                ('matiere', models.CharField(choices=[('phy', 'Physique'), ('chi', 'Chimie')], max_length=3)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('niveau', models.CharField(choices=[('2e', 'Seconde'), ('1re', 'Première Spécialité'), ('1ES', 'Première Enseignement Scientifique'), ('Term', 'Terminale Spécialité'), ('TES', 'Terminale Enseignement Scientifique'), ('TSTL', 'Terminale Stl')], default='2e', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='FicheRevision',
            fields=[
                ('chapitre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='labo_num.chapitre')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='uploads/fiche_js/')),
            ],
        ),
        migrations.CreateModel(
            name='Annale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('lieu', models.CharField(choices=[('métropole', 'Métropole'), ('polynésie', 'Polynésie'), ('mayotte', 'Mayotte'), ('amérique_du_sud', 'Amérique Du Sud'), ('amérique_du_nord', 'Amérique Du Nord'), ('antilles', 'Antilles'), ('pondichéry', 'Pondichéry'), ('asie', 'Asie')], max_length=50)),
                ('annee', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2013), django.core.validators.MaxValueValidator(2023)])),
                ('description', froala_editor.fields.FroalaField(null=True)),
                ('sujet_complet', models.BooleanField(default=False)),
                ('fichier', models.FileField(upload_to='uploads/annales/')),
                ('chapitres', models.ManyToManyField(to='labo_num.Chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('exp', 'Expérimentale'), ('num', 'Numérique'), ('doc', 'Documentaire')], default='doc', max_length=3)),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=150)),
                ('contenu', froala_editor.fields.FroalaField(null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='uploads/activites/')),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labo_num.chapitre')),
            ],
        ),
    ]
