# Generated by Django 3.2.20 on 2023-07-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0002_animation_animationcategory_genially'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animationcategory',
            options={'verbose_name': "Catégorie d'animation", 'verbose_name_plural': "Catégories d'animation"},
        ),
    ]
