# Generated by Django 3.2.20 on 2023-07-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0003_alter_animationcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='img',
        ),
    ]
