# Generated by Django 3.2.20 on 2023-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0004_remove_chapitre_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genially',
            options={'verbose_name_plural': 'geniallies'},
        ),
        migrations.RemoveField(
            model_name='ficherevision',
            name='fichier',
        ),
        migrations.AddField(
            model_name='ficherevision',
            name='fiche',
            field=models.JSONField(default="[{'type': 'notion', 'contenu': '', 'texteA': '', 'texteB': '', 'texteC': ''},]"),
        ),
    ]
