# Generated by Django 3.2.20 on 2023-07-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0007_alter_chapitre_fiche_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
