# Generated by Django 3.2.20 on 2023-07-24 18:36

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0008_chapitre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='description',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='contenu',
            field=froala_editor.fields.FroalaField(null=True),
        ),
    ]
