# Generated by Django 3.2.20 on 2023-07-24 20:30

from django.db import migrations, models
import labo_num.models


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0010_alter_chapitre_fiche_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='fiche_revision',
            field=models.JSONField(default=labo_num.models.Chapitre.defaultJSON),
        ),
    ]
