# Generated by Django 3.2.20 on 2023-07-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0011_alter_chapitre_fiche_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='contenu',
            new_name='description',
        ),
    ]
