# Generated by Django 3.2.20 on 2023-07-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0013_chapitre_notions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activite',
            new_name='Document',
        ),
    ]
