# Generated by Django 3.2.20 on 2023-07-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0014_rename_activite_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_activite',
            field=models.CharField(choices=[('cours', 'Cours'), ('exos', 'Exercices'), ('exp', 'Activité Expérimentale'), ('num', 'Activité Numérique'), ('doc', 'Activité Documentaire')], default='doc', max_length=6),
        ),
    ]
