# Generated by Django 3.2.20 on 2023-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0015_alter_document_type_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
