# Generated by Django 3.2.20 on 2023-07-27 18:09

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0016_alter_document_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('exp', 'Expérimentale'), ('num', 'Numérique'), ('doc', 'Documentaire')], default='doc', max_length=6)),
                ('numero', models.IntegerField(null=True)),
                ('titre', models.CharField(max_length=150)),
                ('contenu', froala_editor.fields.FroalaField(null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='uploads/activites/')),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labo_num.chapitre')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
