# Generated by Django 3.2.20 on 2023-07-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0017_auto_20230727_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='cours',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cours/'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='exercices',
            field=models.FileField(blank=True, null=True, upload_to='uploads/exercices/'),
        ),
    ]
