# Generated by Django 3.2.20 on 2023-07-28 08:53

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labo_num', '0018_auto_20230727_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='contenu',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='description',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
